/* THIS FILE IS FOR PAYLOAD REST API */
import { REST_POST, REST_GET, REST_DELETE, REST_PUT, REST_PATCH } from '@payloadcms/next/routes'

export { REST_POST as POST, REST_GET as GET, REST_DELETE as DELETE, REST_PUT as PUT, REST_PATCH as PATCH }